### ISSUE TITLE
"Segmentation fault (core dumped)" error when attempting to record to GIF

### ISSUE THREAD

**Issue by marc2377** [ArsenArsen/KShare#20] opened 2017-07-13 19:20 UTC
I configured KShare to record as GIF. Then I resized the Area Selection window, and pressed Enter. The program crashed after about 500ms with this output:

> Output #0, gif, to '/tmp/KShareTemp-6273-16:13:05/res.gif':
    Stream #0:0: Unknown: none
Segmentation fault (core dumped)

A gif file of 800 KiB was saved to that location; it was corrupt, however.

**Comment by ArsenArsen** [comment] 2017-07-13 19:21
I knew about this issue but nothing about it's cause, I am looking further into it though.

**Comment by ArsenArsen** [comment] 2017-07-13 19:23
Actually, apparently the core was dumped. If you can, send me the core. If you are worried about sensitive data, you can find my PGP key here: https://keybase.io/arsenarsen

**Comment by marc2377** [comment] 2017-07-13 19:45
Is it enough if I post the output of `coredumpctl info` and the gdb backtrace?

I ask because I don't know how to use PGP. But I can learn if necessary, just not right now.

Thanks.

**Comment by ArsenArsen** [comment] 2017-07-13 19:51
Yes it is. That's all I needed to get from the coredump anyways.

**Comment by marc2377** [comment] 2017-07-13 20:01
Alright. Attached:

[coredump info.txt](https://github.com/ArsenArsen/KShare/files/1146502/coredump.info.txt)
[gdb bt.txt](https://github.com/ArsenArsen/KShare/files/1146501/gdb.bt.txt)

**Comment by ArsenArsen** [comment] 2017-07-13 20:41
Oh. There are no debugging symbols. I didn't think of that.
Could send the executable too? I'd need to disassemble some addresses.

**Comment by marc2377** [comment] 2017-07-13 22:50
Absolutely.


[kshare.zip](https://github.com/ArsenArsen/KShare/files/1146875/kshare.zip)

**Comment by marc2377** [comment] 2017-07-13 23:21
I built a version with `options=(debug !strip)` in PKGBUILD as instructed here: https://wiki.archlinux.org/index.php/Debug_-_Getting_Traces

[coredump info (debug).txt](https://github.com/ArsenArsen/KShare/files/1146922/coredump.info.debug.txt)
[gdb bt.txt](https://github.com/ArsenArsen/KShare/files/1146920/gdb.bt.txt)
[kshare (debug).zip](https://github.com/ArsenArsen/KShare/files/1146921/kshare.debug.zip)

**Comment by marc2377** [comment] 2017-07-13 23:24
I built a version with `options=(debug !strip)` in PKGBUILD as instructed here: https://wiki.archlinux.org/index.php/Debug_-_Getting_Traces

[Uploading coredump info (debug).txt…]()
[gdb bt.txt](https://github.com/ArsenArsen/KShare/files/1146926/gdb.bt.txt)
[Uploading kshare (debug).zip…]()

**Comment by ArsenArsen** [comment] 2017-07-14 10:08
Amazing! Only reason I needed you to do all this is because I could not reproduce this for the life of me. The core dump would still be useful, for me to inspect the memory, but I can make some assumptions like this too.

**Comment by marc2377** [comment] 2017-07-14 20:41
Oh I will upload the dump file later then.

It should contain only the memory data for this application, right? If that's the case I have nothing to worry. Or do you know what sensitive information might be in it?

Also I forgot to mention, in the Settings I had also changed the destination to "clipboard".

Interestingly, though, now after changing the output format to MP4 and then back to GIF, the error no longer happens. (Good thing I had saved the dump file).

However I get a new error: "Destination file exists". Guess that's probably the issue you appear to have fixed in #18. Will test with latest dev. version later.

**Comment by ArsenArsen** [comment] 2017-07-14 21:53
Indeed, #18 is theoretically fixed with one commit on dev. And yes it only has the process memory.
The memory can only have a screenshot in it as far as I am aware.

**Comment by marc2377** [comment] 2017-07-15 19:21
Here you go.

[kshare core dumps.zip](https://github.com/ArsenArsen/KShare/files/1150567/kshare.core.dumps.zip)

ps. I got this:

> There is no assurance this key belongs to the named user
> sub  rsa2048/AF2B1FAE6B5A4803 2016-12-18 ArsenArsen
> (...)
> It is NOT certain that the key belongs to the person named
> in the user ID.  If you *really* know what you are doing,
> you may answer the next question with yes.
> 
> Use this key anyway?

Please bear with me as I'm new to GPG/PGP et al. Is that expected? (From a quick web search I found this is probably because not many users have marked your key as "trusted".)

Thanks.

**Comment by ArsenArsen** [comment] 2017-07-15 20:30
That worked. Looking into it.

**Comment by ArsenArsen** [comment] 2017-07-15 22:25
Could you try the commit from this morning? Also, another helpful thing would be to compile KShare manually like this:
```bash
git clone https://github.com/ArsenArsen/KShare.git
cd KShare
qmake "CONFIG += debug qml-debug" KShare.pro
make -j$(($(nproc) + 1))
```
```

**Comment by ArsenArsen** [comment] 2017-07-25 07:27
Happen to me with debug symbols. I'll see what and if I can do anything

**Comment by RaymondSchnyder** [comment] 2017-10-17 06:53
This also happens when screenshoting an area and editing this area "drawing"

**Comment by ArsenArsen** [comment] 2017-10-17 12:08
What? Only known bug with the editor is in the dev branch and its switching pens from blur to something else crashing. Can you explain a bit better and in more details what happens

**Comment by ArsenArsen** [comment] 2017-10-18 14:45
Since there's been no updates nor clear reproduction steps I'm closing the issue.

Reopen if something changes.

**Closed by ArsenArsen** 2017-10-18 14:45 UTC
Labels: bug, help wanted
