### ISSUE TITLE
Multiple KShare Instances in task Manager

### ISSUE THREAD

**Issue by xaanit** [ArsenArsen/KShare#28] opened 2017-08-01 14:35 UTC
Windows 10

Opening and closing KShare makes multiple instances in the Task Manager. 

![](https://anna.is-a-good-waifu.com/fa1fe6.png)

**Comment by ArsenArsen** [comment] 2017-08-01 14:36
Are you sure those are not threads?

**Comment by charlesmilette** [comment] 2017-08-18 22:18
Yes because the task manager does not shows threads.

**Comment by ArsenArsen** [comment] 2017-08-18 22:57
I don't know then. Help wanted

**Comment by GlitchMasta47** [comment] 2017-09-02 13:44
_(assuming you're developing in Visual Studio for your Windows version)_

As for Windows development, this is sometimes normal for when you incorrectly set up the app settings. Well, not incorrectly, but there's a flag somewhere in Visual Studio (projectName.settings or something like that, I haven't used VS in a while) and it's called something about having only one process at a time. I'm sorry for not having any exact names or anything, soon I'll have my Windows 10 installation back up with Visual Studio to update my answer with the actual text. As for that, it only allows KShare Windows binaries to be run one at a time, so if it's already open and you open the EXE binary, it'll just focus the KShare window, without making a completely different process.

Again, sorry for not enough specific details since I have my Windows installation broken right now, as I said I'll get it fixed with more helpful and exact information in a few days when it's fixed.

**Comment by ArsenArsen** [comment] 2017-09-02 13:52
Who says I develop on Windows?

**Comment by GlitchMasta47** [comment] 2017-09-02 13:55
That is true.
> assuming you're developing in Visual Studio

**Comment by ArsenArsen** [comment] 2017-09-02 13:56
No, I mean I don't develop on Windows at all. The only Windows development I've done is a tiny amount in VBox and Qt Creator

**Comment by GlitchMasta47** [comment] 2017-09-02 13:58
Well, I don't have any experience at all with Qt Creator, but I might as well install it and look around in it to find it.

**Comment by ArsenArsen** [comment] 2017-09-02 14:00
The thing is, this issue has nothing to do with any sort of development enviroment.

I am simply not experienced enough with Windows to qualify to answer and/or research into this issue.

**Comment by GlitchMasta47** [comment] 2017-09-02 14:06
~~Well I am, but I mean... My Windows installation is a little borked up and sick.~~

I'm installing Qt right now, so I'll try and tinker around with it and see what I can find.
For now, the issue isn't too bad, you just have all of the processes running at the same time.

**Comment by ArsenArsen** [comment] 2017-10-18 14:43
@GlitchMasta47 how's that going?

**Comment by ArsenArsen** [comment] 2017-12-06 22:29
Closing as there has been no new updates for a while.

**Closed by ArsenArsen** 2017-12-06 22:29 UTC
Labels: help wanted

**Comment by GlitchMasta47** [comment] 2017-12-08 18:05
Man, I've been pretty dead. As for your 2-day-ago reminder, I finally found something in the documentation about this. I couldn't really find an actual checkbox choice like there is in VS, but I've found a few code samples that have some different ways to prevent multiple instances running at once.
# Using QLockFile
> when a temporary file is created, which is destroyed when the application is closed. Thus at the second instance of the application starts happening on the existence of the file and check if the file already created one open application instance, the second instance is automatically closed;
```cpp
#include "widget.h"
#include <QApplication>
#include <QLockFile>
#include <QDir>
#include <QMessageBox>
 
int main(int argc, char *argv[])
{
    QApplication a(argc, argv);
 
    QLockFile lockFile(QDir::temp().absoluteFilePath("<uniq id>.lock"));
 
    /* Trying to close the Lock File, if the attempt is unsuccessful for 100 milliseconds, 
     * then there is a Lock File already created by another process. 
     / Therefore, we throw a warning and close the program
     * */
    if(!lockFile.tryLock(100)){
        QMessageBox msgBox;
        msgBox.setIcon(QMessageBox::Warning);
        msgBox.setText("The application is already running.\n"
                       "Allowed to run only one instance of the application.");
        msgBox.exec();
        return 1;
    }
 
    Widget w;
    w.show();
 
    return a.exec();
}
```
(Replace \<uniq id\> with an identifier, like com.arsenarsen.kshare or something like that)
# Using QSystemSemaphore and QSharedMemory
(This has a little bit longer explanation)
> In a first variant, it is given a simple and convenient solution to the problem by limiting the number of running instances of Qt applications. But the decision on QLockFile has disadvantages in the sense that there may be a problem with the permissions of the user. And also, if you want to limit, run a single instance of the program for the entire computer, not the differences, how many user sessions can be run on it, then use QLockFile also does not provide this capability.
>
>QSharedMemory the contrary is shared for all users at the same time working at a computer. Therefore, if one of your users to run the program, the latter will not be able to run it.
>
>But in this case, it is necessary not to forget about the differences in the shared memory by the various platforms. In the case of Windows, shared memory will be freed when a normal completion of the program, and at the end of the emergency. In the case of Linux/Unix in case of emergency when crashes memory will not be freed.
>
>The semaphore code presented below is used to solve the problem of race in the case of the simultaneous launch of multiple instances of the same application. The semaphore is created with the meter, the maximum number of which is equal to 1. When lifting the semaphore, all other instances of the application does not have access to the shared memory and thus one copy of wholly owned resources. This copy checks for running another instance of the application by the presence of a shared memory segment identifier corresponding to the application. A copy of the shared memory segment was successfully launched and creates if not found information about another application instance. After that, the semaphore is lowered, allowing another instance of the application tried to run.
>
As with the first sample, replace \<uniq id\> and \<uniq id2\> with an identifier.
```cpp
#include "mainwindow.h"
#include <QApplication>
#include <QSystemSemaphore>
#include <QSharedMemory>
#include <QMessageBox>
 
int main(int argc, char *argv[])
{
    QApplication a(argc, argv);
 
    QSystemSemaphore semaphore("<uniq id>", 1);  // create semaphore
    semaphore.acquire(); // Raise the semaphore, barring other instances to work with shared memory
 
#ifndef Q_OS_WIN32
    // in linux / unix shared memory is not freed when the application terminates abnormally,
    // so you need to get rid of the garbage
    QSharedMemory nix_fix_shared_memory("<uniq id 2>");
    if(nix_fix_shared_memory.attach()){
        nix_fix_shared_memory.detach();
    }
#endif
 
    QSharedMemory sharedMemory("<uniq id 2>");  // Create a copy of the shared memory
    bool is_running;            // variable to test the already running application
    if (sharedMemory.attach()){ // We are trying to attach a copy of the shared memory
                                // To an existing segment
        is_running = true;      // If successful, it determines that there is already a running instance
    }else{
        sharedMemory.create(1); // Otherwise allocate 1 byte of memory
        is_running = false;     // And determines that another instance is not running
    }
    semaphore.release();       
 
    // If you already run one instance of the application, then we inform the user about it
    // and complete the current instance of the application
    if(is_running){
        QMessageBox msgBox;
        msgBox.setIcon(QMessageBox::Warning);
        msgBox.setText("The application is already running.\n" 
                       "Allowed to run only one instance of the application.");
        msgBox.exec();
        return 1;
    }
 
    MainWindow w;
    w.show();
 
    return a.exec();
 }
```
(I literally just got all of this content from [this](https://evileg.com/en/post/147/) website)

**Comment by ArsenArsen** [comment] 2017-12-08 18:39
Well, I leave a decision upon you. Either implement the first method (the second one is overkill, unless you want new opens to signal the old one to show the main window) so you can have that shiny contributor badge, or just say the word and I'll be on it. I am hugely grateful for your research by the way.

**Comment by GlitchMasta47** [comment] 2017-12-10 05:34
You're welcome.

As for the decision, I just decided on using the simple lock file method. For showing the main window, if it detects the lock file then it will open the main window.

I will send out the pull request within the next 24-ish hours.

**Comment by GlitchMasta47** [comment] 2017-12-10 05:42
PR has arrived!
https://github.com/ArsenArsen/KShare/pull/48
