### ISSUE TITLE
Secondary instances of KShare can crash on quitting

### ISSUE THREAD

**Issue by L1Q** [ArsenArsen/KShare#16] opened 2017-07-04 20:56 UTC

**Comment by ArsenArsen** [comment] 2017-07-04 20:57
Could you run the secondary instance from cmd and post the output. I think it's a QHotkey bug with unregistering hotkeys of another process (possible, if you have hotkeys).

**Comment by ArsenArsen** [comment] 2017-07-04 20:58
Also, I am labeling it as [windows] as I cannot reproduce on Linux.

**Comment by L1Q** [comment] 2017-07-04 20:59
I think I don't have any hotkeys and when running from cmd it does not return any output to cmd.

**Comment by ArsenArsen** [comment] 2017-07-04 20:59
Hmm.
I'll try and reproduce this on my Windows VM

**Comment by L1Q** [comment] 2017-07-04 21:00
Correction: it's not rly happening every time, but one of secondary instances would crash

**Comment by ArsenArsen** [comment] 2017-07-05 11:12
Yes, I can reproduce this.

**Comment by ArsenArsen** [comment] 2017-07-05 11:28
![](http://i.imgur.com/HQ9LEqZ.png)

guhhh what

**Comment by ArsenArsen** [comment] 2017-12-06 22:29
Closing as there has been no new updates for a while.

**Closed by ArsenArsen** 2017-12-06 22:29 UTC
Labels: help wanted, windows
