### ISSUE TITLE
Main window does not show up

### ISSUE THREAD

**Issue by ohmyarch** [ArsenArsen/KShare#30] opened 2017-08-12 13:02 UTC
Installed from AUR.
Both `kshare` and `kshare-git` have the same issue.

**Comment by ArsenArsen** [comment] 2017-08-12 13:03
Which window exactly please? And which WM/DE

**Comment by ohmyarch** [comment] 2017-08-12 13:10
"When you start the app (with no arguments, discussed later) a window is popped up, and a tray icon is made." Actually, no window showed up.
DE: KDE Plasma 5.10.4

**Comment by ohmyarch** [comment] 2017-08-12 13:13
And no tray icon, either

**Comment by ohmyarch** [comment] 2017-08-12 13:19
It did start. I can see it in process list.

**Comment by ArsenArsen** [comment] 2017-08-13 17:29
One of people I know using KDE could not reproduce it. Try to run it with `-v` and post the output

**Comment by ohmyarch** [comment] 2017-08-14 04:06
Already tried `-v`, no output.

**Comment by ArsenArsen** [comment] 2017-08-14 10:51
Can't reproduce 🤔

**Comment by jkhsjdhjs** [comment] 2017-09-09 18:35
Same issue here using KDE Plasma on Arch Linux. Also no output running it in verbose mode. If I run it it stays open with 3 child processes, but nothing happens. No window or tray icon appears. Tried `kshare` and `kshare-git`.

**Comment by ArsenArsen** [comment] 2017-09-09 18:43
By now I've tried on Gentoo, Fedora, Debian, Ubuntu, even Mint. They all worked. Other Arch users I know that use KDE also do not have this issue. Only distro I had KDE on was Fedora though, but DE's should be irrelevant.

**Comment by jkhsjdhjs** [comment] 2017-09-09 18:46
Yes, they should be. But it's odd that it's not running on @ohmyarch or on mine and we're both using KDE.
Is there anything I can do to provide helpful information for solving the problem?

**Comment by ArsenArsen** [comment] 2017-09-09 18:47
Nothing I can think of.

**Comment by jkhsjdhjs** [comment] 2017-09-09 19:00
Ok, it's depending on the widget style used in KDE. By default there are Breeze, Fusion, MS Windows 9x and Oxygen. I also have kvantum there because the theme I'm using (Arc-Kde) looks better with kvantummanager. And apparently kshare works with Breeze and Oxygen, but not with Fusion, MS Windows 9x or kvantum.

**Comment by ArsenArsen** [comment] 2017-09-09 19:01
I used Arc-KDE too for a while in development of it.

**Comment by jkhsjdhjs** [comment] 2017-09-09 19:09
If you currently have a working KDE setup you can go to System Setting -> Application Style -> Widget Style and change it to Fusion or MS Windows 9x. With that you should be able to reproduce the issue.

**Comment by ArsenArsen** [comment] 2017-09-09 19:15
I could not reproduce it.

**Comment by jkhsjdhjs** [comment] 2017-09-09 19:27
Ahh, ok. It's also depending on the icon theme...
It's not working with [Papirus](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme) and Fusion, MS Windows 9x or kvantum. With the Breeze icon theme it's also working for me with MS Windows 9x and Fusion.
If you have time you can install the [Papirus Icon Theme](https://aur.archlinux.org/packages/papirus-icon-theme-git/) and use it together with Fusion or MS Windows 9x as Widget Style. Then you are definitely able to reproduce it. But I think that this is not an issue of your tool, I think there's something wrong with the icon theme.

**Comment by ArsenArsen** [comment] 2017-09-14 00:20
Forgot to mention due to hurrying to school: I was not able to reproduce it this way either.

**Comment by jkhsjdhjs** [comment] 2017-09-15 20:43
@ohmyarch what themes are you using? maybe we can find out what we have in common this way and conclude what the problem could be.

**Comment by ohmyarch** [comment] 2017-10-19 13:25
@jkhsjdhjs
Theme: Arc KDE
Icons: Papirus

**Comment by jkhsjdhjs** [comment] 2017-10-19 13:42
Does it work for you when you switch to the Breeze Icon Theme @ohmyarch?

**Comment by ohmyarch** [comment] 2017-10-20 01:06
@jkhsjdhjs Yes, it works.

**Comment by Aareon** [comment] 2017-11-16 18:45
So this is specific to the icon theme? Your icon theme may be trying to overwrite the applications icon, failing, and giving up without reverting to the applications icon. Though, that doesn’t necessarily explain why the window fails to open.

Best guess I can make is missing dependencies. Even then, though, doing `-v` should spit *something* out.

**Comment by ArsenArsen** [comment] 2017-11-16 19:05
yea it'd not even start

**Comment by ArsenArsen** [comment] 2017-12-06 22:30
Closing as there has been no new updates for a while.

**Closed by ArsenArsen** 2017-12-06 22:30 UTC
Labels: cannot-reproduce
