### ISSUE TITLE
.deb link leads to 404

### ISSUE THREAD

**Issue by Trophonix** [ArsenArsen/KShare#53] opened 2018-01-12 08:52 UTC
The "Ubuntu .deb" link goes to a 404 page: https://nativeci.arsenarsen.com/job/KShare%20Stable/lastSuccessfulBuild/artifact/packages/simpleName.deb

**Comment by jellz** [comment] 2018-01-12 08:55
and the proper link doesn't even download.

**Comment by ArsenArsen** [comment] 2018-01-12 13:55
Duplicate of #29

Read the last comment

**Closed by ArsenArsen** 2018-01-12 13:55 UTC

**Comment by Trophonix** [comment] 2018-01-21 04:07
That doesn't solve the issue, though.. you need to change the links in the readme, not just wait for people to ask and then link them to the correct link

**Comment by ArsenArsen** [comment] 2018-01-21 10:19
I added a note but I won't be updating the links until a release because I don't have links which are up and running other than the development ones.
