### ISSUE TITLE
Custom uploader multipart example

### ISSUE THREAD

**Issue by DerEnderKeks** [ArsenArsen/KShare#36] opened 2017-08-31 18:21 UTC
Hello, could you please give me an example of a custom uploader configuration that does the following:

* POST request (`multipart/form-data`) to `http://my.cool/endpoint`
  * form field `apikey` set to `someapikey`
  * form field `file` set to the image data
* Copies JSON node `url` from the reply

I don't really understand the documentation for custom multipart uploaders and how to specify form fields and their values.

I made a ShareX custom uploader configuration once which does the same as I described here. You can find it [here](https://gist.github.com/DerEnderKeks/20ce8b9f6966f395be18e844ba722aa6) for reference.
And a  `curl` request doing this would look like this:
```
curl "http://my.cool/endpoint" -# -F "apikey=someapikey" -F "file=@/path/to/file"
```

**Comment by ArsenArsen** [comment] 2017-09-01 19:54
Sorry it took me this long - I was away for a bit. But here you go:
```json
{
    "name": "wow",
    "target": "https://nothing.domains/api/upload/pomf",
    "format": "multipart-form-data",
    "headers": {
        "Authorization": "i-see-you-are-curious"
    },
    "body": [
        {
            "__Content-Type": "/%contenttype/",
            "filename": "/image.%format/",
            "name": "files[]",
            "body": "/%imagedata/"
        }
    ],
    "return": ".files.0.url",
    "return_prepend": "https://i-am-going-back-to-school.please-kill.me/"
}
```

This file for me is located in `~/.config/KShare/uploaders/nothing.uploader` and is for https://nothing.domains/ which is pomf-compatable.

Pomf docs: http://pomf.readthedocs.io/en/latest/api.html#example-request.

For your particular case, the uploader contents would be:
```json
{
    "name": "wow",
    "target": "http://my.cool/endpoint",
    "format": "multipart-form-data",
    "body": [
        {
            "__Content-Type": "/%contenttype/",
            "filename": "/image.%format/",
            "name": "file",
            "body": "/%imagedata/"
        },
        {
            "body": "apikey",
            "name": "apikey"
        }
    ],
    "return": ".url"
}
```

**Comment by YaManicKill** [comment] 2017-09-01 20:11
Oh, huh. I've not had a chance to try yours out, but I obviously misunderstood how the multi part body array worked. I'll try this out tomorrow. Sorry .

**Comment by DerEnderKeks** [comment] 2017-09-01 21:36
It doesn't seem to work with that uploader configuration.

I modified it like this:
```json
{
  "name": "Yanius (Local)",
  "desc": "",
  "target": "http://127.0.0.1:3000/api/upload",
  "format": "multipart-form-data",
  "body": [
	{
            "__Content-Type": "/%contenttype/",
            "filename": "/image.%format/",
            "name": "file",
            "body": "/%imagedata/"
        },
	{
            "body": "2e449283e39f6a2e9cff8c89959b238c75b41479679e97d3de7014d4e1e15697",
            "name": "apikey"
        }
    ],
  "return": ".url"
}
```

The POST request KShare is doing looks like this:
<details>
<summary>HTTP request</summary>

```
POST /api/upload HTTP/1.1
Content-Type: multipart/form-data
MIME-Version: 1.0
Content-Length: 29181
Connection: Keep-Alive
Accept-Encoding: gzip, deflate
Accept-Language: en-US,*
User-Agent: Mozilla/5.0
Host: 127.0.0.1:3000

--boundary_.oOo._Njk5NjIzMzcxNTU1MjQyODkxMTU4MTcyNTQ5NQ==


	!U58A5AEntrust.net Certification Authority (2048)"Q~#H6#H6QL6QL6 	010U
Entrust.net1@0>U7www.entrust.net/CPS_2048 incorp. by ref. (limits liab.)1%0#U(c) 1999 Entrust.net Limited1301U*Entrust.net Certification Authority (2048)00`Qe0@0d!!U@!@!"`"!0p!U@!7`!@AEntrust.net Certification Authority (2048)imits liab.)!@!Entrust.net@!U
8A51P	1		1$	!!0
sh]J<0"0i3%.!=Y)=Xv{08Vmy_<RR~WYUrhpujs2D.t;mq-  c)-^N!a4^[4@_zfwHfWWTX+O0V{]O^51^@yxj87.}>pUA2s*n|!Lu]xf:1D3@ZIg'O9X$\Fdivv=Y]BvizHftKc:=E%D+~am3K}!p,A`cDvb~d3Cw!T)%lRQGt&Auz_?A[P1r"	|Lu?c!_ QkoOE_ ~
&i/-a}ldhVwpJx\_)V6I]Dcf#=ymkT<C@PR;ikh''0gM:>Y9"SD]Pz}b!
sf`_m5|Z8xM Gr20Y.qVjoPmhz6z$	Pz#aB) Ad&LPAq=?Mp#J2	Ok t094!U2qI(PMMuACDO,6E#SlogUFL?n(Zy&bJGJgf~[A;;cTQ*xIaPOBl
C:qM&5]b2+TWJ'Sm[h#QVSu)w!G=uf~ !AnkaraA51 	1E-Tugra Sertifikasyon Merkezi10!u !@!Staat der Nederlanden!U
8A5!p!@!NL@!U8A5!p}aA5#H6#H6QL6QL6`2`!080326111817Z!`1	!200325110310Z1Lq10	Unl10U
staat der nederlanden1+0)U"staat der nederlanden root ca - g2!"`@!U58A51/vlgothi1`@0Z10	UNL10U
Staat der Nederlanden1+0)U"Staat der Nederlanden Root CA - G20.!Kr!Po!U 8A5!r!@!0@!U8A5??y!o1		!*H!AX7(7 sans@1Eater10b5`or!A
Eater Caps!/;!/hh!/4@AElectrolize!/0!/N !/@[0AEmblema One! /!0/ >!@/@'A	
EnriquetaaXXX{sYZTXTXTXT`1EstebanQq@:ssPAEuphoria Script!  !P AKaushan Script!/g`!/@7p! /0A
Keania One!/0Lc!/%!/CA	
Krona One!/'!/P!/D1LemonQmofilesPA
Lilita One!`/ 0!p/pD!/pHA	
Limelight!/+'! /0P!0/p)QLoved by the King1Mate! QMerriweather Sans!p/T !/ 1/0 01CabinQ4S2LB3zm@PQNothing You Could DoQppp9j@	reAk09-01 23:05:25.p@@@APinyon Script! /8p@	!0/P	!/0"`	1Allura1*T@!_[a1BasicMy!/$ !/H  1/ @0! !/@	! /@0%P	!0/@`	A	Almendra!/!/!!/PJ7AAlmendra SC 	~*C?#H6`Fp8@p8@aX9 X@QL6a!I.[.1AndadaQC,,,,,ZNA	
Andada SC!p/0.`!/:0!/)
A	Arizonia!/!/!/@TAButcherman Caps1g`servicesiant0! !`6451Abel1pb)@an!g @	
Amethysta! /pi!0/@s!@/*aAnnie Use Your Telescope!/pP"!/pq0"!/pd`	"!/ "aAnonymous Pro for Powerline!@./y!!P./k!!`./!!p./p!AAnonymous Pro!/PP! /p`!0/`jp1Arapey1@@body0 P_?!` !A>CASirinStencil!/g!/!/P$A
Sonsie One!/@ l	!/`H	!/t	1Spirax1777!)#H63H6A	Sriracha!@/!P/P]!`/x1Stoke1PkvbH04e!@ QSue Ellen Francisco !/0! /V
10/B @0ASupermercado!' !0 1LobsterQ`>b`0	nP1JaldiQjldmdns4_minimalP1Plaster1@7)7`0!. $/ACabin Condensed!@/P!!P/P8p!`/`A	Capriola! /'D!0/0!@/;f1DosisQsinisplusPALobster Twoappi9P`A	
Rochester@!p !/t!/041/ 6Q0AMarck Script`6`60pt@3H63H63H61Mate SC1	
 sc!pPgroupA
Medula One!p/iR!/P!/*0AMetal Maniaa93#V{aw^l6+igL`t
h1MolleQ?J#H6@PQMountains of Christmas1Ovo0!4@6A	
Nixie One!/P4@! /p
!0/>PANoticia Text! /`
!0/@`
!@/@e
1Play1Z|!>1Qwigley1an!|A	Rosarivo!/@\A!/0/F!/`jzARuge Boogie!/ k
!/&}
!/
1Ruthiey!0/ !@/ 1P/ 0! Av#cp3permercado@QSwanky and Moo Moo!/p!/r1/xo0AText Me One!/pq!/! /`QThe Girl Next Door!0/	!@/@ 	1P/Q01UnlockQ/imageformats@PAVampiro One!@~/<!P~/ !`~/0aAVast Shadowa;<--boundary_.oOo._Njk5NjIzMzcxNTU1MjQyODkxMTU4MTcyNTQ5NQ==


	!U58A5AEntrust.net Certification Authority (2048)"Q~#H6#H6QL6QL6 	010U
Entrust.net1@0>U7www.entrust.net/CPS_2048 incorp. by ref. (limits liab.)1%0#U(c) 1999 Entrust.net Limited1301U*Entrust.net Certification Authority (2048)00`Qe0@0d!!U@!@!"`"!0p!U@!7`!@AEntrust.net Certification Authority (2048)imits liab.)!@!Entrust.net@!U
8A51P	1		1$	!!0
sh]J<0"0i3%.!=Y)=Xv{08Vmy_<RR~WYUrhpujs2D.t;mq-  c)-^N!a4^[4@_zfwHfWWTX+O0V{]O^51^@yxj87.}>pUA2s*n|!Lu]xf:1D3@ZIg'O9X$\Fdivv=Y]BvizHftKc:=E%D+~am3K}!p,A`cDvb~d3Cw!T)%lRQGt&Auz_?A[P1r"	|Lu?c!_ QkoOE_ ~
&i/-a}ldhVwpJx\_)V6I]Dcf#=ymkT<C@PR;ikh''0gM:>8S8388888888PALa Belle Aurore!8.s.!BhH!8.s.1LedgerQ@dgfiles0PALily Script One!P,a!.Z.!,p<N`wQLondrina Outline!/[t !/` 1 / 0ALondrina Shadow!/PlP!/``!/0F-pQLondrina SketchP!p QChau Philomene One!01/P@!!@+/!1P+/!ats0A	
Chela One!/c!/`7!/5ACherry Swash!0/P!@/p	!P/	1ChivoQ8A	
Condiment!o!o!.s!.!p7kAConvergence!P/
!`/
!/T@ACrete Round!&6!pA@1tar fill@AGive You Glory!/  5@
!/$oP
!/@
1Gudea1x!QVAHeadlandOne!/!/F! /AHermeneus One!/px!/ !/l{A	Homenaje!@/n!P/|!`/P@1IcebergQ`YE6yJ1Itim1\_im0!!

AGermania One!p%!.`./!JAGilda Display!/@P!/?! /&AGlass Antiqua!0/zZ!@/0f!P/ N.A	Graduate@!`/Y	!p/P	!/p	AGreat Vibesa78boundary_.oOo._Njk5NjIzMzcxNTU1MjQyODkxMTU4MTcyNTQ5NQ==`AHenny PennyaA5+L6p v9`@Iceland@!f !

AAlfa Slab One!/ (lp!/!/3@AArbutus Slab!@/Y!P/0!`/@1AryaQD&C&1AsapQ`>b  8wP1Asul1PktbJ!01AverageQ(_@PAAverage Sans6#H6f!G ! E9 @"tX}6`6mu$$mu`$$u66`6mu J%@%t7 7eu 36`6Ru@36`6Yui)FEnu0r`6`_60our`6`_6%nui)FEm i)F"t@}6`6%t>6`6F/Et>6`6u0`6`_69upf`6`_6eFuf`6`_69uf`6`_6u36`6u36`6et }6`6EuX;6`6muI%@%t`7 7Su;6`6%*<j9=9|Guf`6`_6UD&tD&!2 1VT3231`C`networks0A
Yellowtail!p/!/ m!/P
A	Aclonica!/ P!/]!/m	AAguafina Script!/&v!/)0! /0'@1AkronimQ`YE601Aladin1PkxbF! in!AAlegreya Sans!%/!&/7!&/(>QAlegreya Sans SC!]!`x 11Ruluko18!s..1Sanchez1M6@5P!pethersASansita One!/ae!/p7!/V1Sedan1PkkbU1`n!!}A	Sedan SCG!/p0!@/!P/@$A	
Sevillana!`/'`!p/pBp!/T1SignikaQ36 CpUp-ASnowburst One!@ !A>XAClicker Script!P/p!`/!p/PsA	Codystar!/P^! / 
!0/P	1ComboQ0+pPAComing Soon !!!.+/!3!L!.P!.AConcert One!@/0H0
!P//5@
!`/@l 
1CopseQ`>b  )	P1Corben{16K!@1Cuprum!A@`h?ctcherman c@A
Changa One!P/`p
!`/PqZp
!p/`
AContrail One!/py!/`&!/qA	
Erica One!/6/
! /P
!0/>PA	
Italiannoa3H6`3H6`3H6#H60^_QLove Ya Like A Sister!0/P`!@//@1P/(Pk0A	
Marko OneQ!z!.s!.! 	y!oid_section`/! !/!/0v! /`,A
CantoraOne!/!/p!/.ACarrois Gothic!0/0P!@/Pn,`!P/`pQCarrois Gothic SC!/!/%1/Prl0QCedarville Cursive!//P!!//!1//p>!01ChangaQ@P)@P1Chango1M6p& !`a@nter!] #H6a#H6#H6pppp1q6oJA	
Fauna One!	/	!
/	!
/0	1FelipaQ36wpmAFinger Paint!Z..! P=!c..A
Fjalla Onea=>--boundary_.oOo._Njk5NjIzMzcxNTU1MjQyODkxMTU4MTcyNTQ5NQ==--

```

</details>

First of all, the `Content-Type` doesn't have the required boundary value. Secondly, the data of the body itself is pure nonsense, as it consists of the names of random certificate authorities and fonts mixed with random characters.

Compared to that, a successful cURL request would look like this:
<details>
<summary>HTTP request</summary>

```
POST /api/upload HTTP/1.1
Host: 127.0.0.1:3000
User-Agent: curl/7.53.1
Accept: */*
Content-Length: 18166
Expect: 100-continue
Content-Type: multipart/form-data; boundary=------------------------98f5e155df842497

--------------------------98f5e155df842497
Content-Disposition: form-data; name="apikey"

addfe1c8bb4f0325b8d7bffac436d117cdb605cc254379d8a9f80f6b207c555e
--------------------------98f5e155df842497
Content-Disposition: form-data; name="file"; filename="screenshot_2017-09-01_23.06.33.png"
Content-Type: application/octet-stream

PNG

<REDACTED PNG DATA>
--------------------------98f5e155df842497--
```

</details>

**Comment by YaManicKill** [comment] 2017-09-02 20:59
Oddly, when running this I get a Seg fault.

```
Zeus KShare (master) $ ./KShare -v
Segmentation fault (core dumped)
```

Config (certain things removed)

```
{
    "name": "ymk",
    "target": "https://domain/api/upload",
    "format": "multipart-form-data",
    "desc": "Blah",
    "body": [
        {
            "__Content-Type": "/%contenttype/",
            "filename": "/image.%format/",
            "name": "file",
            "body": "/%imagedata/"
        },
        {
            "body": "my-api-key",
            "name": "apikey"
        }
    ],
    "return": ".url"
}
```

**Comment by ArsenArsen** [comment] 2017-09-06 16:30
Can you run it with debug symbols and gdb to get me a backtrace?

**Comment by YaManicKill** [comment] 2017-09-12 08:57
> Can you run it with debug symbols and gdb to get me a backtrace?

Sorry, I've not done any of this type of development, how do I do this?

**Comment by ArsenArsen** [comment] 2017-09-12 09:01
```bash
git clone --recursive https://github.com/ArsenArsen/KShare.git
cd KShare
mkdir build
cd build
qmake "CONFIG += debug" ../KShare.pro # Also try qmake-qt5
make -j$(($(nproc) + 1))
gdb src/KShare
# In GDB
r
# Crash it somehow
bt
# Post the output
```

**Comment by YaManicKill** [comment] 2017-09-12 09:13
Hmm, when doing that (using the same configuration) it doesn't crash at all. Running the new binary created with the debug symbols on it's own doesn't crash either (but also doesn't upload correctly, has the issues as mentioned before). But the original binary I created still has a segfault.

**Comment by ArsenArsen** [comment] 2017-09-21 21:35
Since I cannot reproduce it, I'll close the issue. Re-open if you find consistent repro steps

**Closed by ArsenArsen** 2017-09-21 21:35 UTC
Labels: question

**Comment by miraris** [comment] 2018-05-13 22:53
Same issue here
here's the backtrace:
```
Starting program: /home/miraris/Documents/KShare/build/KShare 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffe47db700 (LWP 26132)]
[New Thread 0x7fffe38bd700 (LWP 26133)]
[New Thread 0x7fffe0890700 (LWP 26134)]
[New Thread 0x7fffce7e9700 (LWP 26135)]
[New Thread 0x7fffcdf95700 (LWP 26138)]
[New Thread 0x7fffcd794700 (LWP 26139)]

Thread 1 "KShare" received signal SIGSEGV, Segmentation fault.
0x00007ffff394c4ce in QBuffer::size() const () from /usr/lib/libQt5Core.so.5
(gdb) bt
#0  0x00007ffff394c4ce in QBuffer::size() const () from /usr/lib/libQt5Core.so.5
#1  0x00007ffff3f468e9 in ?? () from /usr/lib/libQt5Network.so.5
#2  0x00007ffff3f46bc2 in ?? () from /usr/lib/libQt5Network.so.5
#3  0x00007ffff396c122 in QIODevicePrivate::read(char*, long long, bool) ()
   from /usr/lib/libQt5Core.so.5
#4  0x00007ffff397235c in ?? () from /usr/lib/libQt5Core.so.5
#5  0x00007ffff3f3565f in ?? () from /usr/lib/libQt5Network.so.5
#6  0x00007ffff3ff1791 in ?? () from /usr/lib/libQt5Network.so.5
#7  0x00007ffff3a83052 in QObject::event(QEvent*) ()
   from /usr/lib/libQt5Core.so.5
#8  0x00007ffff4d60fec in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    () from /usr/lib/libQt5Widgets.so.5
#9  0x00007ffff4d689c6 in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib/libQt5Widgets.so.5
#10 0x00007ffff3a51ce0 in QCoreApplication::notifyInternal2(QObject*, QEvent*)
    () from /usr/lib/libQt5Core.so.5
#11 0x00007ffff3a54946 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/libQt5Core.so.5
#12 0x00007ffff3aaec44 in ?? () from /usr/lib/libQt5Core.so.5
#13 0x00007fffe9bf0368 in g_main_context_dispatch ()
   from /usr/lib/libglib-2.0.so.0
#14 0x00007fffe9bf05b1 in ?? () from /usr/lib/libglib-2.0.so.0
#15 0x00007fffe9bf063e in g_main_context_iteration ()
```
